name = "domaniac-domain-manager"
compatibility_date = "2024-12-25"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "domain_manager"
database_id = "84c29e2a-bbc1-403e-83a6-c216741eebe8"

[vars]
JWT_EXPIRY = "24h"
REGISTRATION_ENABLED = "true"
